[tool.poetry]
name = "alumni"
version = "0.0.0"
description = ""
authors = ["Tsvika <tsvikas@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
